### ISSUE TITLE
Explicit vars?

### ISSUE THREAD

**Issue by max-sixty** [go-task/task#495] opened 2021-05-28 16:47 UTC
Firstly — another thanks for this library! It's much more accessible than `make`, and others are starting to use it at my company.

Something that can be confusing for users is understanding what variables need to be supplied for a task, without reading the whole task. As a result, I have a convention of listing them explicitly for each task or file, like:

```yaml
  switch-env:
    vars:
      project: "{{.project}}"
      cluser: "{{.cluster}}"
```

This works well at the task level, but not the file level. So one question and one feature question:

- It doesn't seem to work at the file level; i.e. this will pass an empty string for `{{project}}` when another taskfile sets the var. Removing this definition allows it work. Could I ask why that is?

```yaml
vars:
  project: "{{.project}}"
```

- Is there more general demand for explicitly listing variables by task & file? I would be interested in a `strict` setting that warned if variables were used implicitly, since it makes them difficult to track.

Thanks again

**Comment by d3dc** [comment] 2021-06-26 16:04
I get away with:

```yaml
build:
    vars: 
      IMAGE_NAME: |
        {{
          default fail "IMAGE_NAME not set"
          .IMAGE_NAME
        }}
      IMAGE_TAG: |
        {{
          default fail "IMAGE_TAG not set"
          .IMAGE_TAG
        }}
```

**Comment by d3dc** [comment] 2021-06-26 16:14
having `{{.VAR}}` at the file level will use the current value of .VAR in the context - `null`.

Your subsequent task declarations will inherit that. `default` and `fail` are slim-sprig functions to handle a `null`.

**Comment by d3dc** [comment] 2021-06-27 19:44
So, after looking at it again, you don't have short-circuit evaluations in templates - fail has to be a part of a block.

You could use:
```
{{.VAR | default nil}}
```

and later

```
{{if not .VAR}}
  {{fail "reason"}}
{{end}}
```

There's also probably a template that you could define that gets more into a feature suggestion:
```
{{define "required"}}
  {{with (index . 0)}}
    {{.}}
  {{else}}
    {{(fail (index . 1))}}
  {{end}}
{{end}}
```

```
{{template "required" (list .VAR "VAR is required")}}
```

**Comment by max-sixty** [comment] 2021-06-27 20:22
Thanks @d3dc . That's indeed the sort of feature that I would make this more concise.

**Comment by andreynering** [comment] 2021-07-11 01:32
Hi @max-sixty ,

I think that having a task attribute to validate that given vars are required probably makes sense 👍.

**Comment by fgblomqvist** [comment] 2021-09-15 17:00
I think this would be very handy. Being able to essentially have args for a task feels like a common need, and having optional (with or without defaults) and mandatory ones makes sense. What's the latest on that? What's the format you're proposing @andreynering?

**Comment by dAnjou** [comment] 2022-01-15 16:07
In my experience, it can be quite dangerous to rely on something being available in the environment.

Let's imagine this command:
```
rm -rf {{.PROJECT_ROOT}}/opt
```
You can probably guess what happens if `PROJECT_ROOT` isn't set anywhere.

In such a case, it'd be cool to have a _strict_ mode which ensures that variables are actually set somewhere. I remember this from Jinja which has this: https://jinja2docs.readthedocs.io/en/stable/api.html#jinja2.StrictUndefined

**Comment by nicomeunier** [comment] 2023-03-22 08:54
related to https://github.com/go-task/task/issues/1063

Also from this below suggestion, I didn't find where we could define templates from Taskfile:
> There's also probably a template that you could define that gets more into a feature suggestion:
> 
> ```
> {{define "required"}}
>   {{with (index . 0)}}
>     {{.}}
>   {{else}}
>     {{(fail (index . 1))}}
>   {{end}}
> {{end}}
> ```
> 
> ```
> {{template "required" (list .VAR "VAR is required")}}
> ```

**Comment by andreynering** [comment] 2023-06-17 23:47
Closing as duplicate of #1203 and #1204.

**Closed by andreynering** 2023-06-17 23:47 UTC
Labels: state: duplicate, type: feature, area: variables
