### ISSUE TITLE
Command can not be run in Windows

### ISSUE THREAD

**Issue by tredoe** [go-task/task#319] opened 2020-05-04 15:59 UTC
- Task version: master
- OS: windows 10

A command like ` - cmd: rm -r -fo "$home/foo/"` cann't be run because `task` finds the command in $PATH
```
"rm": executable file not found in $PATH
```

But in Windows, they are in commands which are not in $PATH but they can be run from the shell.

The solution would be do not find the command in Windows systems.

**Comment by chris-garrett** [comment] 2020-05-09 04:39
Can you add a little bit more detail? When you say `rm` can be run from the shell what shell do you mean? msys? cygwin? wsl?

**Comment by tredoe** [comment] 2020-05-09 06:47
I mean Windows Power Shell

**Comment by tredoe** [comment] 2020-05-09 06:50
https://docs.microsoft.com/en-us/powershell/scripting/samples/appendix-1---compatibility-aliases?view=powershell-7

**Comment by tredoe** [comment] 2020-05-09 06:55
So, at Windows other solution would be to check if the command is an alias like *del, erase, rd, rmdir, rm, ri*; it if is not, then could be checked if it exist in $PATH.

**Comment by chris-garrett** [comment] 2020-05-09 18:56
This was a good ticket for me to dive into the code a little bit. I don't use powershell so I learned something today. 

I wanted to reproduce what you are talking about:
```
chris@JUPITER C:\Users\chris\Desktop\projects\gojira\internals\task
$ ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

chris@JUPITER C:\Users\chris\Desktop\projects\gojira\internals\task
$ task ls
"ls": executable file not found in $PATH
task: Failed to run task "ls": exit status 127

chris@JUPITER C:\Users\chris\Desktop\projects\gojira\internals\task
$ powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\chris\Desktop\projects\gojira\internals\task> ls

    Directory: C:\Users\chris\Desktop\projects\gojira\internals\task

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/9/2020  12:07 AM          11595 CHANGELOG.md
-a----         5/9/2020  12:07 AM           1101 LICENSE
-a----         5/9/2020  12:07 AM            731 README.md
-a----         5/9/2020  12:07 AM        5484032 task.exe
-a----         5/9/2020  12:07 AM        5738496 task.lin
-a----         5/9/2020  12:07 AM        6106672 task.mac
-a----         5/9/2020  11:32 AM            104 Taskfile.yml

PS C:\Users\chris\Desktop\projects\gojira\internals\task> .\task.exe ls
"ls": executable file not found in $PATH
task: Failed to run task "ls": exit status 127
```
I used this Taskfile.yml
```
version: '3'
silent: true
tasks:
  ls:
    desc: "testing ls"
    cmds:
      - ls -la
```

Digging into the code I can see that task uses [mvdan/sh](https://github.com/mvdan/sh) to execute `cmd:`. 

According to [this issue](https://github.com/mvdan/sh/issues/408) the author doesn't want to add support for this. 

So that leaves you with a few alternative options: 
1. Use a different shell like msys, cygwin or maybe wsl
2. Put *nix tools on your path. This is what I do personally since I haven't switched to wsl yet. When installing git I select the option to have the tools on the path overriding find etc. This makes windows a lot more usable for me. YMMV. 

HTH

**Comment by andreynering** [comment] 2020-05-09 19:01
Hi @tredoe,

I'm closing this as a duplicate of #197.

We use [mvdan/sh](https://github.com/mvdan/sh) as the shell library and unfortunately it doesn't yet support some core builtins like `rm`, `cp`, `ls`, etc

**Closed by andreynering** 2020-05-09 19:01 UTC

**Comment by sheldonhull** [comment] 2021-08-04 03:08
@andreynering this really snagged me quite a few times.  Is there any solid reference on what isn't supported or maybe what core builtins are supported?

The main reason I switched to go-task over Make was cross platform functionality, but I've run into basic `mkdir` type commands that run fine in a powershell prompt not working. This would mean every single basic folder/directory creation would require me to wrap in OS specific  handling which I really wanted to avoid. 

This would be really useful to point to in the docs so folks know the OS specific limitations. Not sure if there is any reference yet that I missed.

**Comment by andreynering** [comment] 2021-09-06 14:11
@sheldonhull Please keep the discussion on #197 as this is a duplicated issue.

Also, keep in mind there's an upstream issue on https://github.com/mvdan/sh/issues/93.
