### ISSUE TITLE
Task Dependency Environmental Variable Ignored

### ISSUE THREAD

**Issue by elcfd** [go-task/task#351] opened 2020-07-19 18:29 UTC
Hi,

I am having a problem with the following Taskfile:

```yml
version: '2'

silent: true

vars:
  IMAGES: all

tasks:
  default:
    summary: Build, test and release the docker images
    cmds:
      - task: build
      - task: test
      - task: release

  build:
    summary: Build the docker images
    cmds:
      - python3 image_creator.py build {{.IMAGES}}

  test:
    summary: Run the unit test suite
    deps:
      - task: build
    cmds:
      - python3 -m pytest -v --image_names {{.IMAGES}}

  release:
    summary: Push the built images to Dockerhub
    cmds:
      - python3 image_creator.py release {{.IMAGES}}
```
When running:
```
task test IMAGES=fedora-29
```
The build task is called but the value of IMAGES is not overridden and all images are built but only the fedora-29 image is tested.

When either the build or release tasks are called on their own:
```
task build IMAGES=fedora-29
```
the variable overriding is successful and only the fedora-29 image is built or released.

How can I write the Taskfile so that I have the ability to override the IMAGE variable from the command line for the test task and this override is respected in the build dependency task?

- Task version  2.8.1
- Linux (Ubuntu 18.04)

Thanks,

Charlie

**Comment by andreynering** [comment] 2020-07-20 00:34
Hi @elcfd, thanks for opening this issue!

Seems like a duplicate of #336. See also #341.

It's should probably work if you the below (so the argument is considered global):

```bash
task IMAGES=fedora-29 you-task
```

**Comment by elcfd** [comment] 2020-07-20 12:02
Hi @andreynering - thanks for links and the solution.

I understand what is going on now and will lookout for v3 when it arrives.

**Comment by andreynering** [comment] 2020-08-02 21:42
OK. Closing as a duplicate of #336.

**Closed by andreynering** 2020-08-02 21:42 UTC
Labels: duplicate, v3, variables
