### ISSUE TITLE
"includes" path does not resolve {{.HOME}} variable

### ISSUE THREAD

**Issue by piotrkardasz** [go-task/task#670] opened 2022-02-13 18:27 UTC
- Task version: v3.10.0
- Operating System: Ubuntu

### Example Taskfile showing the issue

```yaml
version: '3'

includes:
  action:
    taskfile: "{{.HOME}}/common/Taskfile.yml"
```

I would like to include Taskfile from the home folder but I am getting an error

```
stat /common/Taskfile.yml: no such file or directory
```

When I put `taskfile: "/home/username/common/Taskfile.yml"` it working correctly it looks like a `.HOME` and variables are not resolved in this case

**Comment by ghostsquad** [comment] 2022-04-06 20:01
It looks like variables are not evaluated prior to finding includes. I think this is also by design in v3 in order to avoid confusing behavior. There aren't very well defined "rules" for how/when variables are evaluated.

You may be able to try `taskfile: ~/common/Taskfile.yml` instead.

To be honest, it feels a bit weird to include a taskfile from your home directory... whats in that common taskfile? why isn't this checked into your source code repository?

This might actually be a symptom of not allowing the use of remote includes. This has been asked for here: #556 #380

Let me know if I'm on the right track or not regarding the "root cause" of what you are trying to accomplish.

**Comment by andreynering** [comment] 2022-04-07 22:48
Hi @piotrkardasz,

I'd say that's not officially supported. Most of the time the Taskfiles you are going to import are all on your repository (in subdirectories). I don't have plans to address use cases like this.

I hope you understand 🙂

**Closed by andreynering** 2022-04-07 22:48 UTC
Labels: question, variables
