### ISSUE TITLE
Add Glamour to Support Markdown of Summary and Improve Aesthetics 

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#602] opened 2021-11-13 07:39 UTC
Glamour is a stylesheet based markdown renderer for Go CLI apps. Plenty of other projects are using it including the GitHub CLI. I think we should incorporate it into the base code.

Here's a screenshot of what the summaries could look like:

![](https://camo.githubusercontent.com/116e5c08d3d3cbbdeb1ec211546e6108df400f546eec5cea19b8882519554f5a/68747470733a2f2f73747566662e636861726d2e73682f676c616d6f75722f676c616d6f75722d6578616d706c652e706e67)

I hired a guy to do customizations on Task and he successfully implemented the feature (granted, the current build is broken). I saw it working though at one point. Here's the fork with the code: https://github.com/Pranjalya/task

I can probably implement this feature and open a pull request if you are willing to incorporate this feature in Task.

Ideally, all of the logging should use Glamour styling as well (i.e. `task --list` and the regular output logs). Please let me know your thoughts.

**Comment by andreynering** [comment] 2021-11-28 19:31
Closed as a duplicate of https://github.com/go-task/task/issues/543

**Closed by andreynering** 2021-11-28 19:31 UTC
Labels: feature
