### ISSUE TITLE
Overriding vars in called task not working as expected

### ISSUE THREAD

**Issue by BeyondEvil** [go-task/task#376] opened 2020-09-09 22:43 UTC
macOS Mojave 10.14.6

```bash
$ task --version
Task version: 2.8.1
```

```yml
version: "2"

silent: true

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the GO binary
    vars:
      GOOS: linux
    cmds:
      - echo {{.GOOS}}

  build-darwin:
    desc: Build the GO binary for macOS
    cmds:
      - task: build
        vars: {GOOS: "darwin"}
  
  build-linux:
    desc: Build the GO binary for Linux
    cmds:
      - task: build
        vars: {GOOS: "linux"}
```

Expected output:

```bash
$ task build
linux
$ task build-darwin
darwin
$ task build-linux
linux
```

Actual output:

```bash
$ task build
linux
$ task build-darwin
linux
$ task build-linux
linux
```

What am I doing wrong?

[Manual](https://taskfile.dev/#/usage?id=calling-another-task) says: "**Overriding** variables in the called task is as simple as informing `vars` attribute" (my emphasis)

**Comment by BeyondEvil** [comment] 2020-09-09 22:45
Using the example and calling `write-file` generates: `task: Failed to run task "write-file": 1:19: > must be followed by a word`

**Comment by andreynering** [comment] 2020-09-13 19:15
Hi @BeyondEvil,

That's by design. Your `build` task should probably be like:

```yaml
tasks:
  build:
    desc: Build the Go binary
    vars:
      GOOS: {{default "linux" .GOOS}}
    cmds:
      - echo {{.GOOS}}
```

As you was doing, you were always overriding whatever value is passed as argument by `linux`, because it was fixed in the task.

**Closed by andreynering** 2020-09-13 19:15 UTC
Labels: question, variables

**Comment by BeyondEvil** [comment] 2020-09-14 18:25
Ok, I can't find any mention of that syntax in the documentation and running your example (regardless of version 2 or 3) generates an error:

```
task: can't unmarshal var value
```

@andreynering

**Comment by achton** [comment] 2020-09-27 06:54
@BeyondEvil I believe what is missing here is single quotes around the assignment in `vars:`, ie.

```
      GOOS: '{{default "linux" .GOOS}}'
```

**Comment by BeyondEvil** [comment] 2020-09-28 10:26
> @BeyondEvil I believe what is missing here is single quotes around the assignment in `vars:`, ie.
> 
> ```
>       GOOS: '{{default "linux" .GOOS}}'
> ```

Thank you good sir! @achton

**Comment by bryceschober** [comment] 2020-11-19 01:10
@andreynering The [documentation states](https://taskfile.dev/#/usage?id=calling-another-task):

> Overriding variables in the called task is as simple as informing vars attribute

... But the example there doesn't actually do any *overriding*, it only *sets* unset variables. It would be really helpful to adapt a working example of actually *overriding* a `{{default ...}}` variable value.

... So I opened PR #407 with a modest proposal to do that.
