### ISSUE TITLE
documentation: env option does not override environment settings

### ISSUE THREAD

**Issue by ssbarnea** [go-task/task#1733] opened 2024-08-02 12:37 UTC
Not sure if this is by design or a bug, but clearly specifying "env:" values does not override already defined values existing in system environment before calling taskfile.

If this is expected, it should documented in a highlighted warning notice, so people would not be surprised about its behavior.

My expectation was that it would override because I could use the shell expansion will fallback mechanism if I would not want it to override environment. With current behavior, I have no way to force taskfile to define a specific environment value and ignore system one.

- Task version: Task version: v3.37.2
- Operating system: any
- Experiments enabled: no

Effective example at https://github.com/ansible/vscode-ansible/blob/main/Taskfile.yml#L17-L18 -- where we cannot force our own `VIRTUAL_ENV` value if the user defined his own in his shell.

**Comment by pd93** [comment] 2024-08-03 14:19
Duplicate of #1038. There is an experiment being released soon that will invert the default behaviour. Stay tuned

**Closed by pd93** 2024-08-03 14:19 UTC
Labels: state: needs triage
