### ISSUE TITLE
Vars order matters when it shouldn't. Maps don't have order.

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#1051] opened 2023-03-11 20:27 UTC
Vars are declared as a map in the yaml, however, order matters. This is unintuitive, especially when I end up automatically generating my taskfile based on Jsonnet.

Proposed fix is to support the vars and env fields as being either a map or a list. This makes it backwards compatible and enables better support for consistent ordered evaluation.

EDIT:

Maps don't have order. Yaml/Json parsers may arbitrarily reorder maps. Arrays/Lists/Slices have order. If order matters, don't use a map. That's the root of this issue.

**Comment by andreynering** [comment] 2023-03-11 21:09
Hi @ghostsquad,

Although vars are indeed a map, since the v3 release order *is* actually respected. This change was made so declarations like this work:

```yaml
vars:
  FOO: 'foo'
  FOOBAR: '{{.FOO}}bar'
  FOOBARBAZ: '{{.FOOBAR}}baz'
```

**Comment by ghostsquad** [comment] 2023-03-12 00:01
Oh, I must have an old release

**Comment by ghostsquad** [comment] 2023-03-12 01:02
@andreynering

I have this version of Task installed:

```
Task version: v3.22.0 (h1:sW+qi054ReRpX7nG8DcKYq3e4IzfSq366RcqEq2lDxc=)
```

Here's the problem:

```yaml
vars:
  APP_IMAGE: docker.io/ghostsquad/foo:{{.GIT_COMMIT}}
  CURRENT_GO_VERSION:
    sh: asdf current golang | awk '{ print $2 }'
  DEBIAN_IMAGE: debian:{{.DEBIAN_VERSION}}-slim
  DEBIAN_VERSION: 11.5
  DEBIAN_VERSION_CODENAME: bullseye
  EXPECTED_GO_VERSION: 1.20.2
  EXPECTED_GO_VERSION_SHORT: |
    {{slice (.EXPECTED_GO_VERSION | splitList ".") 0 2 | join "."}}
  GIT_BRANCH:
    sh: |
      if [ "${CI:-}" == "true" ]; then
        echo "${GITHUB_REF_NAME}";
      else
        git branch --show-current; fi
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GIT_COMMIT_SHORT:
    sh: git rev-parse --short=8 HEAD
  GOLANG_BUILDER_IMAGE: golang:{{.CURRENT_GO_VERSION}}-{{.DEBIAN_VERSION_CODENAME}}
tasks:
  build:
    cmds:
    - |
      docker buildx build \
        --tag {{.APP_IMAGE}} \
        --build-arg GOLANG_BUILDER_IMAGE={{.GOLANG_BUILDER_IMAGE}} \
        --build-arg DEBIAN_IMAGE={{.DEBIAN_IMAGE}} \
        {{.BUILD_ARGS}} \
        .
    label: build with {{.BUILD_ARGS}}
    run: once
    vars:
      BUILD_ARGS: '{{.BUILD_ARGS}}'
```

```
task: [build with --output=type=docker] docker buildx build \
  --tag docker.io/ghostsquad/foo: \
  --build-arg GOLANG_BUILDER_IMAGE=golang:1.20.2-bullseye \
  --build-arg DEBIAN_IMAGE=debian:-slim \
  --output=type=docker \
  .

[+] Building 0.0s (0/0)
ERROR: invalid tag "docker.io/ghostsquad/foo:": invalid reference format
task: Failed to run task "build": exit status 1
```


but if I reorder this map to this the following, it works:

```yaml
 TODO Var order matters, but since this file is dynamically generated from jsonnet, we lose ordering
# Regenerating this file will result in problems.
# !!! Don't forget to fix the ordering in the interm
# https://github.com/go-task/task/issues/1051
vars:
  CURRENT_GO_VERSION:
    sh: asdf current golang | awk '{ print $2 }'
  GIT_BRANCH:
    sh: |
      if [ "${CI:-}" == "true" ]; then
        echo "${GITHUB_REF_NAME}";
      else
        git branch --show-current; fi
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GIT_COMMIT_SHORT:
    sh: git rev-parse --short=8 HEAD
  DEBIAN_VERSION: 11.5
  DEBIAN_IMAGE: debian:{{.DEBIAN_VERSION}}-slim
  DEBIAN_VERSION_CODENAME: bullseye
  EXPECTED_GO_VERSION: 1.20.2
  EXPECTED_GO_VERSION_SHORT: |
    {{slice (.EXPECTED_GO_VERSION | splitList ".") 0 2 | join "."}}
  GOLANG_BUILDER_IMAGE: golang:{{.CURRENT_GO_VERSION}}-{{.DEBIAN_VERSION_CODENAME}}
  APP_IMAGE: docker.io/ghostsquad/foo:{{.GIT_COMMIT}}
```

```
task: [build with --output=type=docker] docker buildx build \
  --tag docker.io/ghostsquad/foo:b7bba2a8285b280a9b9d738376336dc566b8e1fc \
  --build-arg GOLANG_BUILDER_IMAGE=golang:1.20.2-bullseye \
  --build-arg DEBIAN_IMAGE=debian:11.5-slim \
  --output=type=docker \
  .
  
[+] Building 18.1s (19/19) FINISHED
```

**Comment by ghostsquad** [comment] 2023-03-12 01:06
@andreynering I've updated the title to better reflect the problem. There's no guarantees about ordering when dealing with maps. Keys can get resorted arbitrarily, and it shouldn't change behavior. Golang was one of the first languages to essentially _introduce_ bugs into code that relied on the order in which items were added to a map in order to discourage that behavior.

When order matters, use an array/list/slice.

**Comment by andreynering** [comment] 2023-03-12 01:11
@ghostsquad Yes, this is expected behavior. Task evaluates vars in order so it's possible to include one into another in a deterministic manner. On v2 this didn't work right, but this change was to fix it.

To make that work, we have custom YAML unmarshelling code, and store the keys in order of declaration in a separate array. See:

https://github.com/go-task/task/blob/8717c4c287f9a8b88fe1f30b2c5e9db941e198c2/taskfile/var.go#L11-L37

**Comment by ghostsquad** [comment] 2023-03-12 01:15
@andreynering maps don't have order. That's the bug. There should be no expectation that the keys in a map are ordered. I need a way to evaluate vars in a specific order, therefore, this shouldn't be a map, but a list/array/slice.

Please don't continue to close this issue. There still appears to be a misunderstanding.

**Comment by andreynering** [comment] 2023-03-12 01:21
I know that Go maps are not ordered, but as I said we made custom implementation to allow them to be ordered for vars in Task. They are evaluated top to bottom.

In other words, it already works as you expect without the need of making them an array. As you said reordering your variables made it work.

Am I missing anything?

**Comment by andreynering** [comment] 2023-03-12 01:22
In v2 we evaluated variables twice to make it possible to include one into another, but this was a source of bugs.

**Comment by ghostsquad** [comment] 2023-03-12 01:52
My suggestion is to support either a map or an array in order to guarantee order.

**Comment by pd93** [comment] 2023-03-12 01:54
@andreynering there is potentially a solution here that works for everyone...

A map is by far the nicest syntax for defining these variables. An array really doesn't look very nice and uses a lot more symbols for the same meaning. However, there is a way to evaluate the unordered map in a way that doesn't require any horrible double parsing techniques by using a DAG (My new favourite thing 😆).

When compiling variables, we simply create a set of nodes for each map key and then draw edges between them using the map values that contain other map keys. We can then use the DAG to detect loops (and error if any exist) and then iterate through the graph with a depth-first search, resolving the variables as we go.

This solution would also mean we don't need to use our fancy unmarshaler that stores the order and the map. It also means that anyone generating a Taskfile via a Golang marshaller doesn't need to worry about the fact that the map will be written in a random order (I assume this is @ghostsquad's underlying issue?).

**Comment by ghostsquad** [comment] 2023-03-12 01:56
How would you detect the use of other map keys?

**Comment by pd93** [comment] 2023-03-12 02:04
Given a map:

```yaml
A: myvar
B: {{.A}}
C: foo{{.B}}
```

Some horrible pseudocode:

```
for key in map:
    createNode(key)
for k1 in map:
    for k2, value in map:
         if value.contains(fmt.Sprintf("{{.%s}}", k1)):
              drawEdge(k1, k2])
```

**Comment by ghostsquad** [comment] 2023-03-12 02:23
This only works for the simplest of use cases. The moment someone uses a variable within a function or has any sort of logic, this method of parsing falls apart.

**Comment by pd93** [comment] 2023-03-12 02:28
Yeah, my logic was fairly naive, but the problem you described can be fairly easily fixed. We just want to check for the key name with a preceding `.` that is written inside double curly braces. This should cover templating functions too.

**Comment by ghostsquad** [comment] 2023-03-12 02:30
> Yeah, my logic was fairly naive, but the problem you described can be fairly easily fixed. We just want to check for the key name with a preceding `.` that is written inside double curly braces. This should cover templating functions too.

That's a niave implementation. Many things could look exactly like a variable being used, but aren't.

What happens when the double curly braces are escaped?

**Comment by pd93** [comment] 2023-03-12 02:37
> That's a niave implementation

Yes it is 😆 I wrote it in 2 minutes at 2am in an attempt to be helpful. A very quick Google search shows that this is [solvable problem though](https://stackoverflow.com/questions/60144305/how-to-check-if-a-line-or-string-contains-to-be-templated-variables-in-golang).

**Comment by ghostsquad** [comment] 2023-03-12 04:38
Good call. Use the parse tree to find references. I like that solution!

**Comment by ghostsquad** [comment] 2023-03-12 08:16
I changed my mind. There's still ways to reference variables that cannot be found until runtime.

I see two options:

1. Supports vars as a list (k8s does this too, and scripts in general read top to bottom, so it makes sense to require order)


2. Implement lazily evaluated vars. This requires a syntax change, e.g. `{{.Var "foo"}} `, because `.Var` is actually a function, not a field.

I made an issue describing this somewhere else. Too tired to find it right now.

**Comment by andreynering** [comment] 2023-03-17 02:03
I couldn't find any existing issue about this. I think it was only mentioned on comments here and there.

I just created #1065. I'm still not sure if it is the right direction, but it's an idea we can consider, and even experiment with to see if it works or not.

I'm going to close this issue because I don't want to support arrays if we're possibly change it to something different (the proposal) on the next major version anyway.

**Closed by andreynering** 2023-03-17 02:03 UTC
Labels: question
