### ISSUE TITLE
VSCode / editor integration?

### ISSUE THREAD

**Issue by max-sixty** [go-task/task#444] opened 2021-02-18 05:29 UTC
I'm gradually replacing some of my [.vscode/tasks.json](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks) with `Taskfile.yml`.

The VSCode format has a similar goal, though the functionality and explicitness is arguably dominated by task, as well as being usable from the command line.

Ofc the one advantage the VSCode version has is integration with VSCode... e.g. shortcuts, being able to select a task, getting the outputs parsed and added to the Problems tab.

Any thoughts on adding integrations with editors? I could envisage task becoming a format that different editors coalesce around, rather than each having its own — similar to what's happened with LSPs.

**Comment by notnmeyer** [comment] 2021-02-25 20:01
there's https://marketplace.visualstudio.com/items?itemName=paulvarache.vscode-taskfile but i havent had much luck getting it to work

**Comment by andreynering** [comment] 2021-03-07 18:48
Hi @max-sixty, and thanks for opening this issue!

I'll close this as a duplicate of #135, so we have all the discussion in the same place 😉 

But as @notnmeyer said, there is already a third-party extension created by @paulvarache as you can see [here](https://github.com/paulvarache/vscode-taskfile) and [here](https://marketplace.visualstudio.com/items?itemName=paulvarache.vscode-taskfile).

While I love the idea of having better integration with editor, I have little time to dedicate to it as Task itself requires a lot of time to maintain. So, if anyone is willing to help @paulvarache with his project, or try something different, it would be really welcome!

**Closed** 2021-03-07 18:48 UTC
Labels: duplicate, feature
