### ISSUE TITLE
Dotenv no longer pulled from working directory by default

### ISSUE THREAD

**Issue by TazBruce** [go-task/task#1359] opened 2023-10-02 06:13 UTC
Similar to the [docs](https://taskfile.dev/usage/#running-a-taskfile-from-a-subdirectory), I am using a single taskfile to batch run tasks for multiple subdirectories. To pass in values, there are .env files in each directory. By using the dotenv variable this worked perfectly, however, 3.30.1 introduced a breaking change that prevents this from working.

For instance,
(There are 2 .env files. One in a subdirectory with NAME=Subdirectory and one at the root with NAME=Root)

```
version: 3
dotenv: [".env"]
tasks:
  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmd: echo hello $NAME
```

On 3.30.0, running `task test` will result in `hello Subdirectory`, whereas running it on 3.30.1 will result in `hello Root`. To fix this, we needed to specify dotenv in every task, rather than at the top of the taskfile. If this is the intended functionality, this is a breaking change. Possibly worth releasing it as a major update instead? E.g (3.31.0)? 

- Task version: 3.30.1
- Operating system: MacOS Ventura
- Experiments enabled: No

**Comment by pd93** [comment] 2023-10-02 09:07
Hi @TazBruce. Unfortunately, this is not a bug / breaking change. The bug was actually in 3.30.0 and fixed in 3.30.1. I am able to reproduce the example you gave. However, if you go and run your Taskfile in 3.29.1 or 3.28.0, it works the same way that it does in 3.30.1.

What's actually happening is that when you run a task from a subdirectory, Task will search up the directory tree until it finds a Taskfile. When it finds one, the directory that contains the Taskfile becomes the execution directory and so any top-level `dotenv` declarations will look there for files.

As you've stated, adding `dir: '{{.USER_WORKING_DIR}}'` to each task and specifying the `dotenv` at a task-level will override this with the directory you called Task from. This is quite verbose, but it the correct way to solve your issue right now. We could possibly support a top-level `dir` key in the future, but some thought would have to go into how this would behave.

**Closed by pd93** 2023-10-02 09:07 UTC
Labels: state: needs triage
