### ISSUE TITLE
Cannot override global variables in included Taskfiles since 3.36.0

### ISSUE THREAD

**Issue by MarioSchwalbe** [go-task/task#1588] opened 2024-04-09 13:33 UTC
- Task version: 3.36.0
- Operating system: Linux (probably others)
- Experiments enabled: none

We need 2 task files (see https://taskfile.dev/usage/#vars-of-included-taskfiles):

`Taskfile.yml`:
```yml
version: '3'

includes:
  subA:
    taskfile: DockerBuild.yml

  subB:
    taskfile: DockerBuild.yml
    vars:
      DOCKER_IMAGE: imageOfB

tasks:
  default:
    cmds:
      - task: subA:show   # Uses the default value.
      - task: subB:show   # Used to be `imageOfB`. Now is `default_image`.
```

and `DockerBuild.yml`:
```yml
version: '3'

vars:
  DOCKER_IMAGE: default_image

tasks:
  show:
    cmds:
      - echo "DOCKER_IMAGE = {{.DOCKER_IMAGE}}"
```

Since version 3.36.0 I get:
```bash
$ task
task: [subA:show] echo "DOCKER_IMAGE = default_image"
DOCKER_IMAGE = default_image
task: [subB:show] echo "DOCKER_IMAGE = default_image"
DOCKER_IMAGE = default_image
```

In previous versions it was possible to override variables when including taskfiles changing the second case to:
```bash
$ task
task: [subA:show] echo "DOCKER_IMAGE = default_image"
DOCKER_IMAGE = default_image
task: [subB:show] echo "DOCKER_IMAGE = imageOfB"
DOCKER_IMAGE = imageOfB
```

Is this an intended change? And if yes, how would we implement something like that instead?

**Comment by glenvan** [comment] 2024-04-09 21:39
Same issue here.

Passing in a variable with the intention of overriding a variable that is defined in the top-level `vars:` object of the included file no longer replaces the variable's value.

The workaround is to use the [`default` function](https://go-task.github.io/slim-sprig/defaults.html), as in the test data for (the possible cause) #1533:

```yaml
vars:
  DOCKER_IMAGE: {{ .DOCKER_IMAGE | default "default_image" }}
```

**Comment by jclasley** [comment] 2024-04-16 22:44
FWIW, using an anchor in the vars works:
```yaml
# taskfile A

version: 3

vars:
  VAR: "bar"

tasks:
  echo:
    cmds:
      - echo {{ .VAR }}
---
# taskfile B
version: 3

def: &var
  VAR: "foo"

includes: 
  A: 
    taskfile: Taskfile.A.yaml

tasks:
  echo:
    cmds:
      - task: A:echo
        vars:
          *var
```
which outputs `"foo"`
but that same command with a merge override is then overridden
```yaml
# ...
 echo:
    cmds:
      - task: A:echo
        vars:
           <<: *var
```
echos `"bar"`

-----------
If you're like me and have a bunch of variables that you don't want to hardcode over and over, the anchors proved to be a sufficient workaround.

**Comment by jclasley** [comment] 2024-04-16 22:51
This bug also occurs if the included Taskfile is given a variable at the time of inclusion. It randomly picks a variable. Example:

parent taskfile
```yaml
version: 3

includes:
  a:
    taskfile: ./a
    vars:
       PREFIX: a
  b:
    taskfile: ./b
    vars:
       PREFIX: b
  c:
    taskfile: ./c
    vars:
       PREFIX: c
```

internal taskfile:
```yaml
version: 3

tasks:
   echo: echo {{ .PREFIX }}
```

then from `./a`
```yaml
version: 3

includes:
  internal:
    taskfile: ./internal

tasks:
   echo:
     cmds:
        - task: internal:echo
          vars:
            PREFIX: {{ .PREFIX }}
```

`task -d ./a echo` may print `a` or `b` or `c`. Across my department we have had different results, though I personally have repeatedly gotten the same (incorrect) result on my machine.

**Comment by pd93** [comment] 2024-04-16 23:12
This looks to be related to #1533. I was slightly worried about the potential for this to break Taskfiles at the time. I'll take a more detailed look at this soon.

As an aside - @MarioSchwalbe, I see that in your repro example, you are including the same Taskfile twice with two different namespaces. Is this a common setup for you? The upcoming DAG changes (#1563) which will be included in the next release would actually restrict this functionality. It's not something that I thought would be useful or common at the time. Please let me know if you think otherwise.

**Comment by pd93** [comment] 2024-04-16 23:30
@jclasley I'm not able to reproduce your example. Firstly, `PREFIX: {{ .PREFIX }}` causes an error since the template is not quoted, but even if I fix this, I do not observe the random behaviour you're describing. In fact, I get identical behaviour on v3.35.1 and v3.36.0.

I have assumed that you have a file named `Taskfile.yml` in each of the folders: `a`, `b` and `c` as opposed to files with these names. Can you confirm this? Also, your include to `./internal` is from the same directory. Does this mean you have an `internal` directory inside each of `a`, `b` and `c`?

Could you please double check that your example properly reproduces the behaviour you're seeing and update it if necessary. Thanks.

**Comment by MarioSchwalbe** [comment] 2024-04-18 19:48
> As an aside - @MarioSchwalbe, I see that in your repro example, you are including the same Taskfile twice with two different namespaces. Is this a common setup for you? The upcoming DAG changes (#1563) which will be included in the next release would actually restrict this functionality. It's not something that I thought would be useful or common at the time. Please let me know if you think otherwise.

Yes. This is definitely important as I'm using some sort of utility Taskfile to build multiple projects (in subdirectories) from within a Taskfile in the top-level directory.

**Comment by vmaerten** [comment] 2024-04-20 18:45
Hi @pd93 

I have the exact same use case than @MarioSchwalbe. I've opened an issue to discuss / track it :
-  https://github.com/go-task/task/issues/1606

**Comment by vmaerten** [comment] 2024-05-19 15:30
As @pd93 said, it was decided that this was a bugfix at the time and that the proper way was to use | default as suggested by @glenvan

**Closed by vmaerten** 2024-05-19 15:30 UTC
Labels: state: needs triage
