### ISSUE TITLE
Run Dependancy only once

### ISSUE THREAD

**Issue by sadlil** [go-task/task#96] opened 2018-03-08 08:10 UTC
For a task file like following,
```
version: '2'
tasks:
  default:
    deps:
    - fmt
    - install

  fmt:
    cmds:
    - goimports -w *.go pkg
    - gofmt -s -w *.go pkg

  install:
    deps:
    - fmt
    cmds:
    - go install . ./pkg/...

```

if I run `task` - for runnning the default task it will run the fmt twice. But running twice is not necessary. Add an option to run only once would be better.

**Comment by JulienBreux** [comment] 2018-03-08 09:32
@sadlil just a question. 😊 

Why:
```
tasks:
  default:
    deps:
    - fmt <<<
```

**Comment by smyrman** [comment] 2018-03-08 10:40
Duplicate of #53

**Closed by smyrman** 2018-03-08 10:40 UTC

**Comment by sadlil** [comment] 2018-03-08 10:46
@JulienBreux why not? this is just a small example i gave just an example to illustrate, we could make something much bigger in real use cases, and then you do need this.
I still didn't check for a case where a circular dependency could exists or a dependency execution order though.

@smyrman sorry for the dup, failed to check.

**Comment by smyrman** [comment] 2018-03-08 11:18
No problem @sadlil, let's continue the discussion on #53.
