### ISSUE TITLE
Enhanced Logging Features

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#605] opened 2021-11-13 08:16 UTC
It would be ideal if we could incorporate more advanced logging features with Task. These are several features which I think would be useful:

1. Add ability to suppress "is up to date" messages. For every task, I include an installation task for all the software that it relies on. Sometimes this causes log spam. That said, it would be nice to be able to disable/enable all the different log types. The hiding "is up to date" messages feature is supposedly present in this fork: https://github.com/Pranjalya/task
2. Improve the design of the current logs by adding syntax highlighting. The current logs could be improved by leveraging [Glamour](https://github.com/charmbracelet/glamour) to add syntax highlighting. This could perhaps be an optional feature since many might prefer the speed/stability of raw logs. However, using Glamour could significantly improve end-user experience with syntax highlighting and more beautiful logs.
3. It would be ideal if we had options to completely suppress the built-in logger and be able to specify exactly what messages should show up on task success, failure, etc. This would allow task to be used as a library in other Go CLI apps that do not want to show the end-user all the technical details.
4. It would also be nice to include timestamps for when a task starts and finishes for long running tasks. Combining everything in this feature requests, we could for example, have a task could look like this:

```
---
version: '3'

log_options:
  task_timer: true # Provide support for the start/stop log options below
  verbose: false # Disable built in command logging

tasks:
  sample:
    env:
      HEY: test message
    cmds:
      - echo $HEY
    log:
      error: '❌ There was an error.'
      success: '✔️ Successfully echoed a variable.'
      start: '▶ Sample command started at {{.START_TIME}}'
      stop: '🛑 Sample command finished at {{.STOP_TIME}}'
```

Which would log the following if you ran `task sample`:
```
▶ Sample command started at 8:53:59PM
test message
✔️ Successfully echoed a variable.
🛑 Sample command finished at 8:54:58PM
```

**Comment by andreynering** [comment] 2021-11-28 19:31
Closing as a duplicate of https://github.com/go-task/task/issues/543

**Closed by andreynering** 2021-11-28 19:31 UTC
Labels: feature
