### ISSUE TITLE
executable file not found in $PATH (windows)

### ISSUE THREAD

**Issue by ubermanu** [go-task/task#272] opened 2019-11-30 15:18 UTC
Hello,

When running a task on windows, it can't find the executable of basic sh commands

- Task version: 2.7.1
- Windows 10
- Installed using scoop

Example Taskfile.yml

```
version: '2'

tasks:
  default:
    cmds:
      - touch test.txt
```

Running default task it throws an error:

```
rm test.txt
"rm": executable file not found in $PATH
task: Failed to run task "default": exit status 127
```
Any idea?

**Comment by andreynering** [comment] 2019-12-01 13:47
Hi @ubermanu, and thanks for opening this pull request!

I'm closing this issue since this is a duplicate of https://github.com/go-task/task/issues/197.

What's happening is that some core Unix tools like `touch`, `rm`, `cp`, etc are not available on Windows. #197 is about adding implementation of these core tools to Task itself to make tham always work. While that don't happen, you can run Task in an environment where these tools are available; Git Bash is the easiest one, since it comes with Git for Windows.

**Closed by andreynering** 2019-12-01 13:47 UTC
Labels: question
