### ISSUE TITLE
Vars as optional/required parameters

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#714] opened 2022-04-29 06:04 UTC
Like described in #495 - I too have used tasks like functions, and would like some functionality to declare certain vars as required vs optional.

**Comment by nicomeunier** [comment] 2023-03-22 08:51
related to https://github.com/go-task/task/issues/1063

**Comment by andreynering** [comment] 2023-06-17 23:42
Closing as duplicate of #1203 and #1204.

**Closed by andreynering** 2023-06-17 23:42 UTC
Labels: state: duplicate, type: feature, area: variables
