### ISSUE TITLE
Feature: aliases

### ISSUE THREAD

**Issue by kovetskiy** [go-task/task#340] opened 2020-06-08 08:46 UTC
It would be great to have a sort of aliases for tasks. For example, I have a task `atlas:install` and I'd like to have an alias for `i`.

It could be just a task and it will work well:
```
tasks:
   i:
      cmds: [task: atlas:install]
```
It would be great to have a separated section for such tasks called `aliases` and it would look like
```
aliases:
    i: atlas:install
    p: frontend:bundle
```

@andreynering what do you think about this feature? I could implement it and send PR, if the idea looks good for you.

**Comment by andreynering** [comment] 2020-06-11 20:39
Hi @kovetskiy,

I'm closing this as a duplicate of https://github.com/go-task/task/issues/268.

I see you proposed a different syntax, though. It'd be nice to comment about it on https://github.com/go-task/task/issues/268 so we could discuss about which one would be a better fit.

**Closed by andreynering** 2020-06-11 20:39 UTC
Labels: duplicate
