### ISSUE TITLE
Can not read/add variables from command or task

### ISSUE THREAD

**Issue by geek-merlin** [go-task/task#421] opened 2020-12-22 14:35 UTC
```
version: '3'
tasks:
  default:
    cmds:
      # I want to read a var and process it.
      - echo "Give me some input"
      # I can do it in a single compound command.
      - "read input && echo Input: $input. (does work)"
      # But i did not find a way to use it on the next line.
      - 'echo Input: $input. (wont work)'
      - 'echo Input: {{.input}}. (wont work)'
      # It looks like this is a problem of any var assignment.
      - 'export foo=1; echo Foo: $foo (does work)'
      - 'echo Foo: $foo (wont work)'
      - 'echo Foo: {{.foo}}. (wont work)'
      # Unfortunately, using read in vars:sh: throws, #420.
      # But it would only be a workaround as it provides no flow control.
      # And returning a variable from a task seems not possible too.

```

**Comment by geek-merlin** [comment] 2020-12-22 14:36
See #420

**Comment by geek-merlin** [comment] 2020-12-22 15:02
Memo to me:
- #178 - call task recursively
- #181 - maybe there's a workaround if i grok var precedence better

**Comment by andreynering** [comment] 2021-01-07 13:17
Closing as a duplicate of #178.

**Closed by andreynering** 2021-01-07 13:17 UTC
Labels: duplicate, variables
