### ISSUE TITLE
Add task section to describe its input arguments

### ISSUE THREAD

**Issue by nicomeunier** [go-task/task#1063] opened 2023-03-15 15:40 UTC
It could be nice to have a dedicated section from task section to describe explicitly which are the arguments of the task.

**Current issues:**
- Doing that by variables is a problem because the variables cannot be overwritten.  
- So without the predefined variable, is not obvious an input argument is required without noticing it from its description. It's so error-prone.  
- Using go's template to check if a variable exist or fails otherwise is cumbersome and not readable at all. Example:  
  ```yaml
  my_task:
    vars:
      MY_TASK_ARG: '{{if .MY_TASK_ARG}}{{.MY_TASK_ARG}}{{else}}{{fail "Missing argument MY_TASK_ARG"}}{{end}}'
  ```
- Using go's template to check if a variable exist or use a default value is also cumbersome. Example:
  ```yaml
  my_task:
    vars:
      MY_TASK_ARG: '{{.MY_TASK_ARG | default "my_default_value"}}'
  ```

**Suggestion:**

Having a dedicated `args` section in task section like this:
```yaml
  my_task:
    args:
      MY_ARG_WITH_DEFAULT_VALUE: my_default_value # short-way to define the variable with just a default value
      MY_ARG_REQUIRED:
        required: true
      MY_ARG_WITH_DESCRIPTION:
        desc: argument description that could be printed with `--list`
        default: my_default_value
      MY_ARG_WITH_PREDEFINED_VALIDATOR_INT:
        assert_int: true
      MY_ARG_WITH_PREDEFINED_VALIDATOR_EXISTING_FILE:
        assert_existing_file: true
      MY_ARG_WITH_PREDEFINED_VALIDATOR_ENUM:
        assert_enum: [ option1, option2 ]
        default: option1
      MY_ARG_WITH_CUSTOM_VALIDATOR:
        assert: '{{has . (list "option1" "option2" "option3")}}'
      MY_ARG_WITH_CUSTOM_RANGE:
        assert_int: true
        assert: '{{ and (gt . 0) (lt . 10) }}'
```
Then these arguments could be accessible like variables or environments. But they should be evaluated before variables and environments.

**Comment by malikoth** [comment] 2023-03-26 10:00
This seems like kind of a big change, but also maybe kind of not that big?  I'm not sure.  If this idea is deemed acceptable, I would happily start learning Go to see if I could help with implementation.  This feature is what I came here looking for.  Otherwise, my next best option is to _completely rewrite go-task in Python_ so I can add this functionality.  ><

**Comment by inikolaev** [comment] 2023-04-02 08:30
It would also be great to be able to distinguish between arguments and options. For example I would like to be able to run a command that could look like this:

```
task my-task --option <OPT1> <ARG> 
```

**Comment by andreynering** [comment] 2023-06-17 23:45
Closing as duplicate of #1203 and #1204.

I know you proposed more than that but I think having required variable is probably enough.

Defaults is already possible with the `default` template function.

**Closed by andreynering** 2023-06-17 23:45 UTC
Labels: state: duplicate, type: feature, area: variables

**Comment by malikoth** [comment] 2023-06-17 23:56
FWIW, I don't think this IS a duplicate of either of those above. If you don't want to support command line arguments like what are proposed here, that's fine, but what #1204 implements is not this.

**Comment by andreynering** [comment] 2023-06-18 00:06
Sorry, maybe I was not 100% clear.

It's certainly not fully duplicate, but it is partly duplicate, because this one also suggests a way to have required arguments.

Regarding the proposal as a whole, I think it's a bit too verbose. Also, parts of it are already covered by other means:

- `requires:` is queue to be merged soon
- The [`default` template function](https://go-task.github.io/slim-sprig/defaults.html#default) allow to have a default value for a var

Other proposals like `assert`, `enum` I don't plan to consider at the moment. I think it'd add a certain complexity to the tool.

That said, we have changed opinion on features that were initially rejected in the past. So, opinions are still welcome in this thread if someone want to contribute to the discussion.

**Comment by malikoth** [comment] 2023-06-18 01:40
OK, so Nico can chime in and correct me if I'm misinterpreting his intent behind this ticket, but here's what I came here for.

In the go-task docs, you state that there are several places you can set variables for use in your task command string.

>Variables declared in the task definition
    Variables given while calling a task from another (See [Calling another task](https://taskfile.dev/usage/#calling-another-task) above)
    Variables of the [included Taskfile](https://taskfile.dev/usage/#including-other-taskfiles) (when the task is included)
    Variables of the [inclusion of the Taskfile](https://taskfile.dev/usage/#vars-of-included-taskfiles) (when the task is included)
    Global variables (those declared in the vars: option in the Taskfile)
    Environment variables

What I am looking for are command line arguments, like what @inikolaev showed above. The ability to append a "--debug" or "-d" to my task invocation command, and get a bunch of debug flags added to the command that go-task runs. The ability to add a "-v" to my task invocation and have it append "--verbose" to the command it's running.

Essentially, these are still variables. The only difference is where those come from, and the whole big idea I'm chasing is that I want to be able to specify them on the command line at run time. Technically, yes, you can prepend env variables to the command to insert them into the environment, but that's kind of clunky. Argument parsing often comes with a lot more specificity to it, automatic type conversion, validation etc. That's where all the detailed example that Nico gave in the initial body of this issue comes in. Look at Python's [`argparse`](https://docs.python.org/3/library/argparse.html) module for an idea of what he's trying to allow.

So the meat of this issue as I perceived it is to allow specifying that some variables will be provided on the command line, and then this tool would just need to parse them out. How detailed you want to allow those to be specified could be up for debate. But I don't think just allowing some variables to be marked as "required" is what this issue is about, although that is something that the original description included as part of the "vision" of how this might be used.

**Comment by andreynering** [comment] 2023-06-18 01:54
@malikoth It seems to me that what you want is more advanced than what @nicomeunier originally proposed.

I understand what you want and why you see value on that. Basically, a Taskfile would become a kind of CLI, but implemented in YAML instead of Go. 🙂 

You're not the first one that proposed this, and it's indeed a valid idea, but realistically speaking I don't think Task will ever support it because it'd be a considerable change on how Task work today. For this reason, it'd also be a breaking change to existing users.

I've seem other projects doing things that way, like Tusk:

- https://rliebz.github.io/tusk/
- https://github.com/rliebz/tusk

**Comment by malikoth** [comment] 2023-06-18 03:59
Yeah, you appear to be right. I searched for something like what I was wanting, didn't find it in any issues, open or closed. Maybe I didn't search hard enough. I latched onto this one 'cuz everything here seemed like all of those options for specifying specifics of variables is exactly what you'd need to do what I wanted. Well, thanks for humoring me. :)
