### ISSUE TITLE
Homebrew tap should install shell completions

### ISSUE THREAD

**Issue by zx8** [go-task/task#382] opened 2020-10-02 12:16 UTC
https://github.com/go-task/homebrew-tap should install shell completions from https://github.com/go-task/task/tree/master/completion

Here is an example of how to do it:
- https://github.com/Homebrew/homebrew-core/blob/6a8f5692ae05d70f347ce194d9cd892370712239/Formula/hub.rb#L30-L32

The released `tar.gz` archives will need to package up the completions on release so that they are available for install by Homebrew. Currently, the completions are not included in the release artifacts.

---

Relates to https://github.com/go-task/task/issues/293

**Comment by craighurley** [comment] 2020-10-05 09:39
Related to https://github.com/go-task/task/issues/264

**Comment by andreynering** [comment] 2020-10-12 13:38
Closing as a duplicate of #264

**Closed by andreynering** 2020-10-12 13:38 UTC
Labels: duplicate
