### ISSUE TITLE
Nicer errors when a task is not found

### ISSUE THREAD

**Issue by smyrman** [go-task/task#37] opened 2017-07-06 09:08 UTC
I have noticed a few times that when the Taskfile.yml contains a reference to a non-existent task somewhere, I get a panic in the cyclic dependency checks. It would be nice if we could catch this condition and return a nice error instead, indicating which task reference is invalid.

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1247181]

goroutine 1 [running]:
github.com/go-task/task.(*Executor).HasCyclicDep.func1(0xc42010e000, 0x14, 0x0, 0x0)
	/Users/smyrman/.local/src/github.com/go-task/task/cyclic.go:15 +0x141
github.com/go-task/task.(*Executor).HasCyclicDep.func1(0xc420013d20, 0xc, 0xc4200d6900, 0x0)
	/Users/smyrman/.local/src/github.com/go-task/task/cyclic.go:16 +0x1d5
github.com/go-task/task.(*Executor).HasCyclicDep.func1(0xc420013cc0, 0x7, 0xc4200d6300, 0xc4200cfc00)
	/Users/smyrman/.local/src/github.com/go-task/task/cyclic.go:16 +0x1d5
github.com/go-task/task.(*Executor).HasCyclicDep(0xc4200ee150, 0x12efb51)
	/Users/smyrman/.local/src/github.com/go-task/task/cyclic.go:24 +0x171
github.com/go-task/task.(*Executor).Run(0xc4200ee150, 0xc420013c60, 0x1, 0x1, 0x1, 0x0)
	/Users/smyrman/.local/src/github.com/go-task/task/task.go:64 +0x2f
main.main()
	/Users/smyrman/.local/src/github.com/go-task/task/cmd/task/task.go:93 +0x52f
```

**Comment by andreynering** [comment] 2017-07-06 10:15
Thanks. Should be an easy fix, and we can have a test for it.

**Comment by andreynering** [comment] 2017-07-08 13:30
Fixed in part. By now, Task will ignore invalid tasks and give an error after, and not while doing cyclic detection.

The issue is that tasks can be called with interpolation, and we don't know the value at this moment.

```yml
task:
  deps:
    - task: "task-{{.VARIABLE}}"
  vars:
    VARIABLE: something
```

Maybe move that to "runtime" again in the future?

**Comment by andreynering** [comment] 2017-07-08 16:37
Took a different approach that fixes the above use case.

**Closed** 2017-07-08 16:36 UTC
Labels: bug
