### ISSUE TITLE
Passing Vars as Params to Task

### ISSUE THREAD

**Issue by mellena1** [go-task/task#52] opened 2017-07-14 17:51 UTC
With the new 1.4 release and #32, is something like this supported?
```
some-task:
  cmds:
    - task: my-task
       vars: {var1: {{.VAR}}, var2: {{.OTHER_VAR}}}
  vars:
    VAR: $echo "hello"
    OTHER_VAR: $echo "hi" 

my-task:
  cmds:
    - cmd using var1 and var2
  vars:
    var1: val
    var2: val
```

The reasoning behind this is I'm obviously looking to do more intense commands than echoing a string as my values of VAR and OTHER_VAR. So I can compute my value once and pass it to all of the other tasks I'm running.

Thanks for your tool, it's really awesome!

**Comment by andreynering** [comment] 2017-07-14 18:49
Hi @mellena1 

Yes, we plan to do that to the next release. This actually should already work on master, there's just a little bug as you can see on #40.

I'm closing this s duplicate of #40, but feel free to comment there if you have something to add.

> Thanks for your tool, it's really awesome!

Thanks. 😉

**Closed by andreynering** 2017-07-14 18:49 UTC
Labels: bug

**Comment by mellena1** [comment] 2017-07-14 18:51
Awesome, thanks for the response. Sorry for the duplicate issue, I didn't even see the other one. Its been a long week XD. Keep up the good work!
