### ISSUE TITLE
SIGSEGV on missing "version" attribute

### ISSUE THREAD

**Issue by coffeemicha** [go-task/task#1394] opened 2023-11-09 11:06 UTC
- Task version:  v3.24.0
- Operating system: Ubuntu (WSL)
- Experiments enabled: No

When including a taskfile which does not have a "version" attribute set, a SIGSEGV is thrown

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x617ba9]

goroutine 1 [running]:
github.com/Masterminds/semver/v3.(*Version).Compare(0xc000022f00?, 0x44?)
        github.com/Masterminds/semver/v3@v3.2.1/version.go:406 +0x29
github.com/go-task/task/v3/taskfile/read.Taskfile(0xc000203290)
        github.com/go-task/task/v3@v3.24.0/taskfile/read/taskfile.go:172 +0x1de
```

This should be handled gracefully

**Comment by pd93** [comment] 2023-11-10 01:45
Sounds like a duplicate of #1148.

This was fixed in #1149 and released in [v3.25.0](https://github.com/go-task/task/releases/tag/v3.25.0). Can you please try updating your `task` version and see if it resolves the issue?

**Closed by pd93** 2023-11-10 01:45 UTC
Labels: state: needs triage
