### ISSUE TITLE
v3: color output doesn't work properly on Windows

### ISSUE THREAD

**Issue by wdscxsj** [go-task/task#343] opened 2020-06-12 01:43 UTC
- Task version: 3.0.0-preview4
- Windows version: Windows 10 Enterprise 1909 64-bit

Taskfile.yml:

```
# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - winver
```

Color output doesn't work in cmd.exe and powershell.exe:

![1](https://user-images.githubusercontent.com/863369/84455821-e8d89e80-ac90-11ea-917b-6fb32b8a8a76.png)

Works well in ConEmu and Terminal:

![2](https://user-images.githubusercontent.com/863369/84455827-ebd38f00-ac90-11ea-9c9d-cffab3c1c3bb.png)

With `version: '2'`, it works well in ConEmu and Terminal (with no color), but still fails in cmd.exe and powershell.exe:

![3](https://user-images.githubusercontent.com/863369/84455840-f4c46080-ac90-11ea-976e-e52716410435.png)

Maybe mattn's [colorable](https://github.com/mattn/go-colorable) is a good solution?

**Comment by telenieko** [comment] 2021-04-01 15:41
Just got hit by that. Command help hints that it should be possible to disable colored output, there is a flag to enable it, but it is enabled by default.

```
Options:
  -c, --color             colored output (default true)
```

Either `--no-color` or #459 should be available for us poor windows users without color :(

**Comment by ivotron** [comment] 2021-04-01 16:07
an alternative is to use `--color=false` . does that work on your end?

**Comment by telenieko** [comment] 2021-04-01 19:47
> an alternative is to use `--color=false` . does that work on your end?

That seems to have no effect on windows (v3.3.0)
```
❯ task --color=false test
←[0mtask: Command........
````

**Comment by andreynering** [comment] 2021-05-31 02:00
Hi everybody, thanks for reporting this!

No sure what's happening on Windows. By the screenshots seems that it's not supported on CMD. Did anyone try on PowerShell?

`--color=false` is supported and does work on macOS. Need to check on Windows to see what's happening...

Anyway, just added support for `NO_COLOR=1` as well so perhaps that works for now...

- https://github.com/go-task/task/issues/459
- https://github.com/fatih/color/pull/137

**Comment by telenieko** [comment] 2021-06-03 08:21
> No sure what's happening on Windows. By the screenshots seems that it's not supported on CMD. Did anyone try on PowerShell?

I am on PowerShell Core (Run: pwsh.exe)
 
> `--color=false` is supported and does work on macOS. Need to check on Windows to see what's happening...
> Anyway, just added support for `NO_COLOR=1` as well so perhaps that works for now...

Testing:

```
❯ task test
←[32mtask: [test] echo "hello go-task"
←[0mhello go-task

❯ task test --color=false
←[0mtask: [test] echo "hello go-task"
←[0mhello go-task

❯ $env:NO_COLOR=1
❯ task test
task: [test] echo "hello go-task"
hello go-task
```

**Comment by silvanocerza** [comment] 2021-09-07 14:42
I've investigated a bit this issue and found out some things. 
If you run a task that has more than one task as dependency the colored output doesn't work only for the first one, subsequent ones will have no issues.

e.g.
Running this:
```
  python:lint:
    desc: Lint Python code
    deps:
      - task: poetry:install-deps
    cmds:
      - poetry run flake8 --show-source
```
produces this:

![image](https://user-images.githubusercontent.com/3314350/132362651-70bb7348-a012-43b7-952d-b4276039d424.png)

This line is the "culprit": https://github.com/go-task/task/blob/6c73ab823b5e34430eacbb7b2ec14bd80995a58b/internal/execext/exec.go#L58

You can easily verify that's the cause by changing that line to:
```
	logger.Blue()(opts.Stdout, "NOT COLORED FIRST TIME\n")
	err = r.Run(ctx, p)
	logger.Blue()(opts.Stdout, "COLORED ALWAYS\n")
	return err
```

This is the result:
![image](https://user-images.githubusercontent.com/3314350/132363793-6e27e118-4db6-43d4-86e8-c091317901df.png)

Am not sure how to best fix this issue, I don't have enough knowledge about the codebase. There's probably some strange thing going on with stdout and stderr. 😕 

Hope this helps.

**Comment by pd93** [comment] 2023-06-27 09:14
I've just tried the sample on Windows 11 with Task v3.26 on both `cmd` and `powershell` and it looks fine to me. Since this was reported in the Task v3 preview and no-one has commented or referenced this 
issue for nearly 2 years, I'm going to close it.

If anyone is still having this problem or thinks this isn't fixed, please open a new issue with steps to repro.

**Closed by pd93** 2023-06-27 09:14 UTC
Labels: type: bug, os: windows
