### ISSUE TITLE
Task directory for included Taskfiles

### ISSUE THREAD

**Issue by wtcross** [go-task/task#260] opened 2019-11-05 14:49 UTC
**Task Version**: 2.7.0

It appears that a Task's directory is set to that of the root Taskfile if it is included and doesn't specify its own directory.

https://taskfile.dev/#/usage?id=task-directory

This was unexpected to me since it affects how file paths can be structured in included Taskfiles. The scenario that caused me to look at it this way was to use Task to replace Make for a monorepo. Right now it's working great, but I have to run all tasks from the root of the project if I want it to work. Ideally I'd be able to run the included Taskfiles, which are local to each package in the monorepo.

Is this something on the roadmap? After looking at the code it looks like adding a `Dir` field to the `Taskfile` struct and massaging how tasks are run could enable a Task to have the following level of precedence for its directory:
1. Set at Task level
2. Parent Taskfile (might not be the root directory of the project)
3. Root Taskfile directory

**Comment by wtcross** [comment] 2019-11-05 14:51
I'd try to work on this if you're interested in this sort of contribution. It could break Taskfiles using v2 so I understand it would need to be carefully considered.

**Comment by andreynering** [comment] 2019-11-10 23:15
Hi @wtcross, thanks for opening this issue!

There's [an open issue to track the ability of making included Taskfiles run on its own directory](https://github.com/go-task/task/issues/144). Please let me know of your thoughts (would it suffice your use case?).

Also, [work on v3](https://github.com/go-task/task/issues/195) (on the [v3 branch](https://github.com/go-task/task/pulls)), although slow, is ongoing. So this is the right time to consider adding that.

Contribution is always welcome, but I'll probably do that myself at some point otherwise. In case you want to try, feel free to open a WIP PR and ask for direction/help if needed.

**Comment by andreynering** [comment] 2020-02-14 01:29
@wtcross As this is a duplicate of #144, I'll close this.

And FYI, this is a WIP right now: https://github.com/go-task/task/pull/292

**Closed by andreynering** 2020-02-14 01:29 UTC
Labels: feature
