### ISSUE TITLE
Including globally available functions

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#527] opened 2021-07-22 01:18 UTC
I would like to use my own logger so I can add things like icons and pretty colors. However, the logger `.sh` file I have has initialization logic that takes a second so I cannot call it directly each time. Is there a way I can have Task source the logger `.sh` file once and have it available to all tasks?

**Comment by SwitchedToGitlab** [comment] 2021-07-28 21:21
@ProfessorManhattan not sure I understand what you're requesting.

> source the logger .sh file once and have it available to all tasks?

What do you mean by "have it available to all tasks?" If you could provide some kind of example that would be awesome.

**Comment by andreynering** [comment] 2021-08-01 00:18
Hi @ProfessorManhattan,

Although it's for a slightly different use case, I'll close this as a duplicate of https://github.com/go-task/task/issues/204#issuecomment-495946056 since that could work for this, too.

**Closed by andreynering** 2021-08-01 00:18 UTC
Labels: bug, duplicate
