### ISSUE TITLE
Windows 10 - "sleep": executable file not found in $PATH

### ISSUE THREAD

**Issue by testautomation** [go-task/task#305] opened 2020-03-05 17:04 UTC
Task version: 2.8.0
OS: Windows 10 64 bit

error:
```
echo ... staring EHRbase server ...
... staring EHRbase server ...
java -jar ../application/target/application-0.11.0.jar --cache.enabled=false > log &
sleep 20
"sleep": executable file not found in $PATH
task: Failed to run task "start": task: Failed to run task "starteb": exit status 127
```

example task
```yaml
starteb:
        cmds:
          - echo ... starting EHRbase server ...
          - java -jar ../application/target/application-0.11.0.jar --cache.enabled=false > log &
          - sleep 20
          - echo ... EHRbase server started.
```

### sleep is not supported by Window's cmd.exe

![image](https://user-images.githubusercontent.com/38438046/76004288-86416b00-5f09-11ea-9100-90c462a660fd.png)

### but works in PowerShell

![image](https://user-images.githubusercontent.com/38438046/76004368-acffa180-5f09-11ea-8a94-3b106bb38a8e.png)

task command was executed in "Windows Terminal (Preview)" which uses PowerShell under the hood - not cmd.exe

**Comment by andreynering** [comment] 2020-03-14 20:12
Hi @testautomation,

What happens is that the `sleep` builtin is not implemented on [the shell interpreter Task uses](https://github.com/mvdan/sh), so it unfortunately won't work on Windows for now (which doesn't have a proper executable called `sleep` available).

I'm closing this as a duplicate of #197.

For more information see https://github.com/mvdan/sh/issues/93 and https://github.com/mvdan/sh/issues/97.

**Closed by andreynering** 2020-03-14 20:12 UTC
Labels: duplicate
